---
abstract: "A perl library for Twitter's API v1"
author:
  - 'Marc Mims <mmims@cpan.org>'
build_requires:
  File::Find: 0
  File::Temp: 0
  Test::Fatal: 0
  Test::More: 0
  Test::Simple: 0.98
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300030, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Net-Twitter-Lite
no_index:
  directory:
    - src
    - examples
recommends:
  Net::Netrc: 0
  Net::OAuth: 0.25
requires:
  Carp: 0
  Crypt::SSLeay: 0.5
  Encode: 0
  HTTP::Request::Common: 0
  JSON: 2.02
  LWP::UserAgent: 2.032
  Net::Netrc: 0
  URI: 1.40
  URI::Escape: 0
  overload: 0
  parent: 0
  perl: 5.005
  strict: 0
  warnings: 0
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Net-Twitter-Lite
  homepage: https://github.com/semifor/net-twitter-lite
  repository: https://github.com/semifor/net-twitter-lite.git
version: 0.12000
