---
abstract: 'A perl interface to the Twitter API'
author:
  - 'Marc Mims <marc@questright.com>'
build_requires:
  ExtUtils::MakeMaker: 6.42
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.87'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Net-Twitter-Lite
no_index:
  directory:
    - examples
    - inc
    - src
    - t
recommends:
  JSON::XS: 0
  Net::OAuth: 0.16
requires:
  JSON::Any: 1.19
  LWP::UserAgent: 2.032
  URI::Escape: 0
  perl: 5.005
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Net-Twitter-Lite
  homepage: http://github.com/semifor/Net-Twitter-Lite
  license: http://dev.perl.org/licenses/
  repository: git://github.com/semifor/Net-Twitter-Lite.git
version: 0.04000
